# Generated by Django 4.1 on 2022-09-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
