# Generated by Django 4.1 on 2022-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_mywatchlist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
